const verifyUserRegInfo = require('./verifyUserRegInfo');
const verifyUserLoginInfo = require('./verifyUserLoginInfo');
const verifyJWT = require('./verifyJWT');
const verifyTripId = require('./verifyTripId');
const verifyTrip = require('./verifyTrip');
const verifyUser = require('./verifyUser');
const verifyProfileUpdate = require('./verifyProfileUpdate');
const verifyUserAccessToUsers = require('./verifyUserAccessToUsers');
const verifyNoTripId = require('./verifyNoTripId');

//Custom middleware functions that can be imported into any route file
//for use on routes as needed
//They perform functions to validate the data being sent in is in valid formats
//The JWT is also verified to know it was generated by this system

module.exports = {
    verifyUserRegInfo,
    verifyUserLoginInfo,
    verifyJWT,
    verifyTripId,
    verifyTrip,
    verifyUser,
    verifyProfileUpdate,
    verifyUserAccessToUsers,
    verifyNoTripId
};